
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: cashcash
      # You should definitely change the password in production
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: app
      MYSQL_USER: app
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      UPLOAD_LIMIT: 256M
    depends_on:
      - database

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
